#!/usr/bin/env bash

# Check for tool dependencies
SELF_FULLPATH=`realpath $0`
SELF_DIR=`dirname $SELF_FULLPATH`
# Override default tool list, we only need the one
TOOLS=(mkvpropedit)
# Does not depend on any other scripts
SCRIPTS=NONE
if [ ! -r $SELF_DIR/toolchecker ]; then
    echo "toolchecker not found."
    exit 1
else
    . $SELF_DIR/toolchecker
fi

for FILE in "$@"; do
    $MKVPROPEDIT --add-track-statistics-tags "$FILE"
done
